function T_vf_j0 = finalOptTimePassj0(v0,a0,sf)
%finalOptTimePassj0
%    T_vf_j0 = finalOptTimePassj0(V0,A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    22-Nov-2023 18:09:11

t2 = v0.*5.0;
t4 = 1.0./a0;
t5 = a0.*sf.*8.0;
t7 = sqrt(5.0);
t6 = t2.*v0;
t8 = t5+t6;
t9 = sqrt(t8);
t10 = t7.*t9;
T_vf_j0 = [t4.*(t2+t10).*(-1.0./4.0);t4.*(t2-t10).*(-1.0./4.0)];
end
