function out1 = timeMinVelPass(a0,sf)
%timeMinVelPass
%    OUT1 = timeMinVelPass(A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    22-Nov-2023 18:09:08

out1 = -(sqrt(1.5e+1).*sqrt(-a0.*sf))./a0;
end
