function sf_j0 = finalOptPosj0(v0,a0,T)
%finalOptPosj0
%    SF_J0 = finalOptPosj0(V0,A0,T)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    22-Nov-2023 18:09:08

sf_j0 = T.*v0.*(3.0./5.0)+T.^2.*a0.*(3.0./2.0e+1);
end
