function final_opt_velocity_time_pass_var = finalOptVelPass(v0,a0,sf,T)
%finalOptVelPass
%    FINAL_OPT_VELOCITY_TIME_PASS_VAR = finalOptVelPass(V0,A0,SF,T)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    22-Nov-2023 18:09:08

final_opt_velocity_time_pass_var = ((sf.*-1.5e+1+T.*v0.*7.0+T.^2.*a0).*(-1.0./8.0))./T;
end
