function cost_tot = totalCost(v0,a0,sf,vf,af,T)
%totalCost
%    COST_TOT = totalCost(V0,A0,SF,VF,AF,T)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    22-Nov-2023 18:09:07

cost_tot = 1.0./T.^5.*(T.^3.*(a0.*v0.*2.88e+2+a0.*vf.*1.92e+2-af.*v0.*1.92e+2-af.*vf.*2.88e+2)+T.^2.*(a0.*sf.*-4.8e+2+af.*sf.*4.8e+2+v0.*vf.*1.344e+3+v0.^2.*7.68e+2+vf.^2.*7.68e+2)+sf.^2.*2.88e+3+T.^4.*(a0.*af.*-2.4e+1+a0.^2.*3.6e+1+af.^2.*3.6e+1)-T.*sf.*(v0+vf).*2.88e+3);
end
