function out1 = finalOptTimeStopj0(v0,a0)
%finalOptTimeStopj0
%    OUT1 = finalOptTimeStopj0(V0,A0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    22-Nov-2023 18:09:09

out1 = (v0.*-2.0)./a0;
end
